package com.oldchat.material.core.crypto

import android.util.Base64
import javax.crypto.KeyAgreement
import java.security.KeyFactory
import java.security.KeyPair
import java.security.KeyPairGenerator
import java.security.MessageDigest
import java.security.PublicKey
import java.security.SecureRandom
import java.security.spec.ECGenParameterSpec
import javax.crypto.Cipher
import javax.crypto.Mac
import javax.crypto.spec.IvParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * ECDH + AES-CBC + HMAC-SHA256 implementation.
 * Mirrors HttpAuthHelper.ensureSession from client-guide.md §2.3.
 *
 * Handshake flow:
 * 1. Client generates ephemeral ECDH key pair (secp256r1 / P-256)
 * 2. POST /auth/handshake with client public key (base64)
 * 3. Server returns sessionId + serverPublicKey
 * 4. Derive shared secret via ECDH → encKey (AES) + macKey (HMAC)
 * 5. Encrypt requests: AES-256-CBC with random IV
 * 6. MAC payload: HMAC-SHA256(macKey, encryptedPayload)
 */
object CryptoUtil {

    private const val EC_ALGORITHM = "EC"
    private const val EC_CURVE = "secp256r1" // P-256
    private const val ECDH_ALGORITHM = "ECDH"
    private const val AES_ALGORITHM = "AES/CBC/PKCS5Padding"
    private const val AES_KEY_ALGORITHM = "AES"
    private const val HMAC_ALGORITHM = "HmacSHA256"
    private const val AES_KEY_SIZE = 256
    private const val IV_SIZE = 16 // AES block size

    /**
     * Generate a new ECDH key pair (P-256).
     */
    fun generateKeyPair(): KeyPair {
        val keyPairGenerator = KeyPairGenerator.getInstance(EC_ALGORITHM)
        keyPairGenerator.initialize(ECGenParameterSpec(EC_CURVE))
        return keyPairGenerator.generateKeyPair()
    }

    /**
     * Encode public key to base64 string (X.509 format).
     */
    fun publicKeyToBase64(publicKey: PublicKey): String {
        return Base64.encodeToString(publicKey.encoded, Base64.NO_WRAP)
    }

    /**
     * Decode base64-encoded public key.
     */
    fun base64ToPublicKey(base64Key: String): PublicKey {
        val keyBytes = Base64.decode(base64Key, Base64.NO_WRAP)
        val keyFactory = KeyFactory.getInstance(EC_ALGORITHM)
        val keySpec = java.security.spec.X509EncodedKeySpec(keyBytes)
        return keyFactory.generatePublic(keySpec)
    }

    /**
     * Derive AES encryption key and HMAC key from ECDH shared secret.
     *
     * Steps:
     * 1. Perform ECDH key agreement with our private key + server public key
     * 2. Derive shared secret bytes
     * 3. Split into encKey (first 32 bytes) and macKey (next 32 bytes)
     *
     * @return Pair(encKey: ByteArray, macKey: ByteArray) both 256-bit
     */
    fun deriveKeys(clientKeyPair: KeyPair, serverPublicKey: PublicKey): Pair<ByteArray, ByteArray> {
        val keyAgreement = KeyAgreement.getInstance(ECDH_ALGORITHM)
        keyAgreement.init(clientKeyPair.private)
        keyAgreement.doPhase(serverPublicKey, true)
        val sharedSecret = keyAgreement.generateSecret()

        // 派生顺序（对照 Windows 版 OldChat 源码）：
        // encKey = SHA-256(sharedSecret + "enc")
        // macKey = SHA-256(sharedSecret + "mac")
        val encKey = deriveSubKey(sharedSecret, "enc".toByteArray())
        val macKey = deriveSubKey(sharedSecret, "mac".toByteArray())

        return Pair(encKey, macKey)
    }

    private fun deriveSubKey(secret: ByteArray, info: ByteArray): ByteArray {
        val digest = MessageDigest.getInstance("SHA-256")
        digest.update(secret)
        digest.update(info)
        return digest.digest()
    }

    /**
     * AES-256-CBC encrypt.
     *
     * Format: IV (16 bytes) || ciphertext
     *
     * @param plainText raw bytes to encrypt
     * @param encKey 32-byte AES key
     * @return IV + ciphertext as base64 string
     */
    fun aesEncrypt(plainText: ByteArray, encKey: ByteArray): String {
        val cipher = Cipher.getInstance(AES_ALGORITHM)
        val secretKey = SecretKeySpec(encKey, AES_KEY_ALGORITHM)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)
        val iv = cipher.iv // Random IV generated by cipher
        val encrypted = cipher.doFinal(plainText)
        val combined = iv + encrypted
        return Base64.encodeToString(combined, Base64.NO_WRAP)
    }

    /**
     * AES-256-CBC decrypt.
     *
     * @param encryptedBase64 base64(IV + ciphertext)
     * @param encKey 32-byte AES key
     * @return decrypted bytes
     */
    fun aesDecrypt(encryptedBase64: String, encKey: ByteArray): ByteArray {
        val combined = Base64.decode(encryptedBase64, Base64.NO_WRAP)
        val iv = combined.copyOfRange(0, IV_SIZE)
        val cipherText = combined.copyOfRange(IV_SIZE, combined.size)
        return aesDecryptRaw(cipherText, encKey, iv)
    }

    /**
     * 解密 WS 消息信封（对照 Windows 版 OldChat）：
     * 消息格式为 JSON {iv, data, mac}，其中：
     * - iv: base64(16字节 IV)
     * - data: base64(密文)
     * - mac: base64( HMAC-SHA256(macKey, iv_bytes + ciphertext_bytes) )
     *
     * @param jsonEnvelope 原始 JSON 字符串
     * @param encKey AES 密钥
     * @param macKey HMAC 密钥
     * @return 解密后的明文，失败返回 null
     */
    fun decryptEnvelope(jsonEnvelope: String, encKey: ByteArray, macKey: ByteArray): String? {
        return try {
            val map = com.google.gson.Gson().fromJson(jsonEnvelope, Map::class.java) as? Map<*, *>
                ?: return null
            val ivB64 = map["iv"]?.toString() ?: return null
            val dataB64 = map["data"]?.toString() ?: return null
            val macB64 = map["mac"]?.toString() ?: return null

            val iv = Base64.decode(ivB64, Base64.NO_WRAP)
            val ciphertext = Base64.decode(dataB64, Base64.NO_WRAP)
            val expectedMac = Base64.decode(macB64, Base64.NO_WRAP)

            // 验证 mac：HMAC-SHA256(macKey, iv + ciphertext)
            val mac = Mac.getInstance(HMAC_ALGORITHM)
            mac.init(SecretKeySpec(macKey, HMAC_ALGORITHM))
            mac.update(iv)
            mac.update(ciphertext)
            val actualMac = mac.doFinal()
            if (!MessageDigest.isEqual(actualMac, expectedMac)) {
                return null
            }

            // AES-CBC 解密
            val clear = aesDecryptRaw(ciphertext, encKey, iv)
            String(clear, Charsets.UTF_8)
        } catch (e: Exception) {
            null
        }
    }

    private fun aesDecryptRaw(cipherText: ByteArray, encKey: ByteArray, iv: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(AES_ALGORITHM)
        val secretKey = SecretKeySpec(encKey, AES_KEY_ALGORITHM)
        val ivSpec = IvParameterSpec(iv)
        cipher.init(Cipher.DECRYPT_MODE, secretKey, ivSpec)
        return cipher.doFinal(cipherText)
    }

    /**
     * Compute HMAC-SHA256 of payload.
     *
     * @param payload data to MAC
     * @param macKey HMAC key
     * @return base64-encoded HMAC
     */
    fun hmacSha256(payload: ByteArray, macKey: ByteArray): String {
        val mac = Mac.getInstance(HMAC_ALGORITHM)
        val keySpec = SecretKeySpec(macKey, HMAC_ALGORITHM)
        mac.init(keySpec)
        val hmacBytes = mac.doFinal(payload)
        return Base64.encodeToString(hmacBytes, Base64.NO_WRAP)
    }

    /**
     * Verify HMAC-SHA256.
     *
     * @return true if MAC matches
     */
    fun verifyHmac(payload: ByteArray, expectedMac: String, macKey: ByteArray): Boolean {
        val computed = hmacSha256(payload, macKey)
        return MessageDigest.isEqual(computed.toByteArray(), expectedMac.toByteArray())
    }

    /**
     * Generate a random 16-byte IV.
     */
    fun generateIv(): ByteArray {
        val iv = ByteArray(IV_SIZE)
        SecureRandom().nextBytes(iv)
        return iv
    }
}
